TEST: Clarify output for assert_dict_equal.
Previously, for a large diff, I was getting output that looked like:

```
AssertionError: extra key in result: set([u'timestamp'])
keys do not match
path: _[u'CA'][u'table_1'][u'base'][u'indices'].viewkeys()
result is missing key: set([u'indices'])
keys do not match
path: _[u'CA'][u'table_2'][u'checkpoints'].viewkeys()
extra key in result: set([u'timestamp'])
keys do not match
path: _[u'CA'][u'table_3'][u'base'][u'indices'].viewkeys()
result is missing key: set([u'indices'])
keys do not match
```

This is hard to parse when there's a lot of it, because it's hard to see which
lines should be grouped together.

The same output now looks like:

```
AssertionError: keys do not match
extra key in result: set([u'timestamp'])
path: _[u'CA'][u'table_1'][u'base'][u'indices'].viewkeys()
===
keys do not match
result is missing key: set([u'indices'])
path: _[u'CA'][u'table_2'][u'checkpoints'].viewkeys()
===
keys do not match
extra key in result: set([u'timestamp'])
path: _[u'CA'][u'table_3'][u'base'][u'indices'].viewkeys()
```

This puts the most general statement ("keys to not match") first, followed by
details, and it makes it clearer which lines go together.